### ISSUE TITLE
Option for Enhanced Resolution Parameter Selection

### ISSUE THREAD

**Issue by willforker** [NCALM-UH/CODEM#10]
Tangentially related to my last issue post, wondering what thoughts would be on using `arcpy` in the python toolbox interface (`CODEM\arcgispro\src\coregister\esri\toolboxes\3D Data Co-Registration.pyt`) to automatically generate the best Minimum Resolution (m) parameter to optimize best results and processing time (all if the user wishes, of course). Obtaining the resolution of input DEMs is totally possible, might be possible for LAS files as well (point count and possibly area could yield and average point density?), but a relationship between the input data resolution and ideal CODEM parameter resolution would have to be known. Is this something that has been tested or studied yet? If not, I am willing to play around as I believe this would be a beneficial feature. Would love to discuss further.

-Will

**Comment by j9ac9k** [comment]
What you describe sort of happens right now here:

https://github.com/NCALM-UH/CODEM/blob/main/src/codem/main.py#L341-L344


where `config["MIN_RESOLUTION"]` is the value entered in the toolbox code.  I'm reluctant to ask arcpy to try and get any more clever, as the number of formats that arcpy can read is far more limited than what codem can under the hood.  We could try and extract what the resolution _should_ be after files are selected; but I'm not sure that would buy us much.  I think a well-described tooltip code describing the limitations of this value would go a long way.
