### ISSUE TITLE
Consider swapping out enlighten for rich

### ISSUE THREAD

**Issue by hobu** [NCALM-UH/CODEM#13]
We might consider switching to using [Rich](https://github.com/Textualize/rich) instead of [enlighten](https://python-enlighten.readthedocs.io/en/stable/) for progress reporting.

Some bullets to make the case:

* Rich has a larger developer community and is more actively developed
* Rich is known to work well on all three major platform terminals
* Integration with [Textual](https://github.com/Textualize/textual) if we wanted to make a really fancy interface
* Emoji support?

**Comment by j9ac9k** [comment]
> * Emoji support?

Should have started with that! I'm sold!
