### ISSUE TITLE
Multiple 2D things being computed but never used

### ISSUE THREAD

**Issue by chambbj** [NCALM-UH/CODEM#30]
Simply holdovers from early experimentation and can be removed. `tree2d` and everything derived from it.

https://github.com/NCALM-UH/CODEM/blob/5ed1cb2cc79a97ef763e25ebc366313fa95b3c2b/src/vcd/preprocessing/preprocess.py#L159

**Comment by hobu** [comment]
the bits about colors for plotting can be ditched too. https://github.com/NCALM-UH/CODEM/blob/5ed1cb2cc79a97ef763e25ebc366313fa95b3c2b/src/vcd/preprocessing/preprocess.py#L206

**Comment by j9ac9k** [comment]
> the bits about colors for plotting can be ditched too.
> 
> https://github.com/NCALM-UH/CODEM/blob/5ed1cb2cc79a97ef763e25ebc366313fa95b3c2b/src/vcd/preprocessing/preprocess.py#L206

What about the intermediate products here?

https://github.com/NCALM-UH/CODEM/blob/main/src/vcd/preprocessing/preprocess.py#L241-L271
