### ISSUE TITLE
Toolbox PDAL Driver Path

### ISSUE THREAD

**Issue by willforker** [NCALM-UH/CODEM#31]
When loading ArcGIS Pro toolbox, often the PDAL driver path results in an error when trying to do `import pdal` . Thus, the line `os.environ["PDAL_DRIVER_PATH"] = "C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\neggs-pyproj901\\bin;C:\\Program Files\\ArcGIS\\Pro\\bin\\Python\\envs\\neggs-pyproj901\\Lib\\site-packages\\bin"` has to be incorporated into the toolbox to set the environment correct for certain edge cases.

**Comment by j9ac9k** [comment]
this has been fixed with #34
