### ISSUE TITLE
Naming conventions for VCD outputs

### ISSUE THREAD

**Issue by willforker** [NCALM-UH/CODEM#35]
Might be nitpicking, but it might be useful to somehow incorporate the names of the before/after data into the output ground and non-ground products (meshes, rasters, pcs) so that multiple runs of the tool with different inputs can be differentiated easily in the Arc interface. Simply food for thought, since it is not too hard to change the name of the layer itself in Arc

**Comment by hobu** [comment]
> names of the data

Do you mean file names? A title the user provides as an option?

**Comment by willforker** [comment]
Yup, I meant file names, perhaps given as a text string input parameter.
