### ISSUE TITLE
Annotate raster outputs with GeoTIFF tags

### ISSUE THREAD

**Issue by hobu** [NCALM-UH/CODEM#48]
We should put version information and `CODEM` in GeoTIFF tag output from CODEM so that someone has information about how the data came into being. 

We might also include tags about the fixed and floating data that were used to create the output along with gross error information.

**Comment by j9ac9k** [comment]
What would be an appropriate key/tag name to use, I added `CODEM_VERSION` and put the actual version, is there any other convention I should try and follow?
