### ISSUE TITLE
Colorize the VCD output point cloud

### ISSUE THREAD

**Issue by hobu** [NCALM-UH/CODEM#52]
https://viewer.copc.io/?state=d3d6a54f96222c326657186ecb2879b69fa338380e2cc0306a5077759e115acc is an example that does 🔴 and 🔵 colorization of the change point clouds. We could do the same for an after product.

![image](https://user-images.githubusercontent.com/87751/223828712-9a4d9603-2cf7-41ff-9069-36c5b0fca06e.png)

**Comment by j9ac9k** [comment]
Fixed with #54
