### ISSUE TITLE
SRS error/issue with VCD

### ISSUE THREAD

**Issue by willforker** [NCALM-UH/CODEM#60]
In VCD > preprocessing.py, around line 103 it takes in the SRS from the pipeline.quickinfo, but notes that if there are more than one SRS, it won't work. 
```
       def _get_utm(pipeline: pdal.Pipeline) -> pdal.Pipeline:
            data = pipeline.quickinfo
            is_reader = [[k.split(".")[0] == "readers", k] for k in data.keys()]
            for k in is_reader:
                if k[0]:  # we are a reader
                    reader_info = data[k[1]]
                    bounds = reader_info["bounds"]
                    srs = CRS.from_user_input(reader_info["srs"]["compoundwkt"])
                  
                    # we just take the first one. If there's more we are screwed
                    break
```

Encountered this error with Open Data LiDAR from DC, with a PCS and VCS (see image). Possibly we can make a workaround? If not, I will enhance the toolbox to warn people accordingly.
![image](https://user-images.githubusercontent.com/46581944/225708477-51b0f3c1-95b8-4043-b528-6483c8552b3c.png)

**Comment by willforker** [comment]
source of error: 2018 las data from [here](https://opendata.dc.gov/apps/lidar-grid-tiles/explore).

**Comment by hobu** [comment]
>  Possibly we can make a workaround? If not, I will enhance the toolbox to warn people accordingly.

Throw an error. Not out responsibility to normalize coordinate systems, and it is important that users provide cartesian data too.

**Comment by willforker** [comment]
Are Vertical Coordinate Systems / Datums off the table too?

**Comment by willforker** [comment]
understandable- will add this error/warning to toolbox
